/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FetchDataImport } from './routes/fetch-data'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FetchDataRoute = FetchDataImport.update({
  path: '/fetch-data',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/fetch-data': {
      id: '/fetch-data'
      path: '/fetch-data'
      fullPath: '/fetch-data'
      preLoaderRoute: typeof FetchDataImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, FetchDataRoute })

/* prettier-ignore-end */
